version: "3.8"

services:
  kali:
    build: .
    container_name: kali-pentest
    volumes:
      - ./data:/data
      - ./data/maindb.json:/root/L3MON-2/maindb.json   # <--- Persistencia de contraseña
    ports:
      - "8080:8080"
      - "4444:4444"
    restart: unless-stopped